export const QIUSHI = 'QIUSHI'
export const SQUARE = 'SQUARE'
export const GUANZHU = 'GUANZHU'
export const WODE = 'WODE'
export const DONGTAI = 'DONGTAI'
export const NOTSHOUYE = 'NOTSHOUYE'
export const SHOUYE = 'SHOUYE'